frr version 8.5.2
hostname router-a
log stdout informational
log syslog informational
service integrated-vtysh-config
!
interface eth1
 ip address 10.77.1.1/24
!
interface eth2
 ip address 10.77.0.1/30
!
router bgp 65001
 bgp router-id 10.77.0.1
 no bgp ebgp-requires-policy
 neighbor 10.77.0.2 remote-as 65002
 neighbor 10.77.0.2 description PEER_ROUTER_B
 !
 address-family ipv4 unicast
  network 10.77.1.0/24
  neighbor 10.77.0.2 activate
 exit-address-family
!
line vty
!
